import type { GroceryCategory } from '@/models'

/**
 * Keyword → aisle. This is a shopping convenience, not a taxonomy: getting
 * "cilantro" into Produce saves a lap of the store, and anything unrecognised
 * lands in Other where it is still perfectly usable.
 *
 * Order matters — the first list whose keyword appears in the name wins — so
 * more specific aisles are checked before broad ones (canned tomatoes before
 * fresh tomatoes).
 *
 * These priority phrases are checked before everything else, because a broader
 * keyword would otherwise capture them: "olive oil" is not an olive, and
 * "lemon juice" is not a beverage.
 */
const PRIORITY_RULES: Array<{ category: GroceryCategory; keywords: string[] }> = [
  {
    category: 'Pantry',
    keywords: [
      'olive oil',
      'vegetable oil',
      'canola oil',
      'sesame oil',
      'coconut oil',
      'avocado oil',
      'sunflower oil',
      'peanut oil',
    ],
  },
  {
    category: 'Produce',
    keywords: ['lemon juice', 'lime juice', 'green onion', 'spring onion'],
  },
  {
    category: 'Beverages',
    keywords: ['apple juice', 'orange juice', 'cranberry juice', 'pineapple juice'],
  },
  {
    category: 'Sauces & Condiments',
    keywords: ['tomato ketchup', 'apple cider vinegar'],
  },
]

const RULES: Array<{ category: GroceryCategory; keywords: string[] }> = [
  {
    category: 'Spices & Seasonings',
    keywords: [
      'salt',
      'pepper',
      'peppercorn',
      'cumin',
      'paprika',
      'turmeric',
      'coriander',
      'cinnamon',
      'nutmeg',
      'clove',
      'cardamom',
      'oregano',
      'thyme',
      'rosemary',
      'sage',
      'bay leaf',
      'bay leaves',
      'chili powder',
      'chilli powder',
      'curry powder',
      'garam masala',
      'cayenne',
      'red pepper flake',
      'italian seasoning',
      'onion powder',
      'garlic powder',
      'seasoning',
      'dried basil',
      'dried parsley',
      'dried dill',
      'allspice',
      'ginger powder',
      'ground ginger',
      'vanilla extract',
      'extract',
      'yeast',
      'baking powder',
      'baking soda',
    ],
  },
  {
    category: 'Canned Goods',
    keywords: [
      'canned',
      'can of',
      'crushed tomato',
      'diced tomato',
      'tomato paste',
      'tomato sauce',
      'coconut milk',
      'chickpea',
      'garbanzo',
      'black bean',
      'kidney bean',
      'cannellini',
      'pinto bean',
      'refried bean',
      'baked bean',
      'tuna',
      'sardine',
      'broth',
      'stock',
      'bouillon',
      'olives',
      'black olive',
      'artichoke heart',
      'water chestnut',
      'green chile',
      'pumpkin puree',
    ],
  },
  {
    category: 'Meat & Seafood',
    keywords: [
      'chicken',
      'beef',
      'steak',
      'ground turkey',
      'turkey',
      'pork',
      'bacon',
      'sausage',
      'ham',
      'lamb',
      'veal',
      'brisket',
      'ribs',
      'chorizo',
      'pancetta',
      'prosciutto',
      'salmon',
      'shrimp',
      'prawn',
      'cod',
      'halibut',
      'tilapia',
      'scallop',
      'mussel',
      'clam',
      'crab',
      'lobster',
      'fish',
      'mince',
    ],
  },
  {
    category: 'Dairy & Eggs',
    keywords: [
      'milk',
      'butter',
      'cheese',
      'cheddar',
      'mozzarella',
      'parmesan',
      'feta',
      'ricotta',
      'cream cheese',
      'sour cream',
      'heavy cream',
      'half and half',
      'yogurt',
      'yoghurt',
      'egg',
      'ghee',
      'creme fraiche',
      'buttermilk',
      'cottage cheese',
    ],
  },
  {
    category: 'Produce',
    keywords: [
      'onion',
      'shallot',
      'scallion',
      'green onion',
      'garlic',
      'ginger',
      'carrot',
      'celery',
      'potato',
      'sweet potato',
      'tomato',
      'lettuce',
      'spinach',
      'kale',
      'arugula',
      'cabbage',
      'broccoli',
      'cauliflower',
      'zucchini',
      'squash',
      'pepper',
      'bell pepper',
      'jalapeno',
      'jalapeño',
      'cucumber',
      'mushroom',
      'corn',
      'pea',
      'green bean',
      'asparagus',
      'brussels sprout',
      'eggplant',
      'leek',
      'radish',
      'beet',
      'turnip',
      'parsnip',
      'apple',
      'banana',
      'orange',
      'lemon',
      'lime',
      'grape',
      'berry',
      'strawberry',
      'blueberry',
      'raspberry',
      'mango',
      'pineapple',
      'peach',
      'pear',
      'plum',
      'avocado',
      'cilantro',
      'parsley',
      'basil',
      'mint',
      'dill',
      'chive',
      'herb',
      'salad',
      'sprout',
      'melon',
      'cantaloupe',
      'watermelon',
    ],
  },
  {
    category: 'Bakery',
    keywords: [
      'bread',
      'baguette',
      'roll',
      'bun',
      'tortilla',
      'pita',
      'naan',
      'bagel',
      'croissant',
      'sourdough',
      'brioche',
    ],
  },
  {
    category: 'Pasta & Grains',
    keywords: [
      'pasta',
      'spaghetti',
      'penne',
      'macaroni',
      'linguine',
      'fettuccine',
      'lasagna',
      'noodle',
      'rice',
      'quinoa',
      'couscous',
      'barley',
      'farro',
      'bulgur',
      'oat',
      'cornmeal',
      'polenta',
      'flour',
      'breadcrumb',
      'panko',
      'lentil',
      'orzo',
    ],
  },
  {
    category: 'Sauces & Condiments',
    keywords: [
      'soy sauce',
      'fish sauce',
      'worcestershire',
      'hot sauce',
      'sriracha',
      'ketchup',
      'mustard',
      'mayonnaise',
      'mayo',
      'vinegar',
      'salsa',
      'pesto',
      'hummus',
      'tahini',
      'curry paste',
      'chili paste',
      'bbq sauce',
      'barbecue sauce',
      'honey',
      'maple syrup',
      'jam',
      'peanut butter',
      'dressing',
      'marinade',
      'hoisin',
      'oyster sauce',
      'miso',
    ],
  },
  {
    category: 'Frozen',
    keywords: ['frozen', 'ice cream', 'puff pastry', 'phyllo'],
  },
  {
    category: 'Pantry',
    keywords: [
      'olive oil',
      'vegetable oil',
      'canola oil',
      'sesame oil',
      'coconut oil',
      'oil',
      'sugar',
      'brown sugar',
      'cornstarch',
      'corn starch',
      'nut',
      'almond',
      'walnut',
      'pecan',
      'cashew',
      'pine nut',
      'seed',
      'sesame',
      'raisin',
      'chocolate',
      'cocoa',
      'wine',
      'sherry',
      'mirin',
      'tofu',
      'tempeh',
    ],
  },
  {
    category: 'Beverages',
    keywords: ['juice', 'coffee', 'tea', 'soda', 'sparkling water', 'beer'],
  },
  {
    category: 'Snacks',
    keywords: ['cracker', 'chip', 'pretzel', 'popcorn', 'granola bar'],
  },
  {
    category: 'Deli',
    keywords: ['deli', 'sliced turkey', 'sliced ham', 'rotisserie'],
  },
  {
    category: 'Household',
    keywords: [
      'paper towel',
      'toilet paper',
      'dish soap',
      'detergent',
      'foil',
      'parchment',
      'plastic wrap',
      'trash bag',
      'sponge',
      'toothpaste',
      'shampoo',
    ],
  },
]

export function categorizeIngredient(name: string): GroceryCategory {
  const haystack = ` ${name.toLowerCase()} `
  for (const rule of [...PRIORITY_RULES, ...RULES]) {
    for (const keyword of rule.keywords) {
      if (haystack.includes(keyword)) return rule.category
    }
  }
  return 'Other'
}

/** Staples worth offering when someone first sets up their pantry. */
export const SUGGESTED_PANTRY_STAPLES = [
  'salt',
  'black pepper',
  'olive oil',
  'vegetable oil',
  'garlic powder',
  'onion powder',
  'sugar',
  'flour',
  'rice',
  'soy sauce',
  'vinegar',
  'baking powder',
  'baking soda',
  'butter',
  'chili powder',
  'cumin',
  'paprika',
  'oregano',
  'cinnamon',
  'honey',
]
