import type { RecipeDraft } from '@/models'
import { toRecipeDraft } from '@/services/recipeImport'

/**
 * A dozen recipes to start from.
 *
 * An empty library makes "Plan my week" impossible to try, so MealHelp ships
 * with a small, deliberately practical set: big-batch meals that leave
 * leftovers, appliance meals, and a couple of twenty-minute rescues. They are
 * ordinary recipes written for this app, and they can be edited or deleted like
 * anything else.
 */

interface Seed {
  title: string
  description: string
  servings: number
  prep: number
  cook: number
  active: number
  methods: RecipeDraft['cookingMethods']
  mealTypes?: RecipeDraft['mealTypes']
  tags: string[]
  equipment: string[]
  ingredients: string[]
  steps: string[]
  notes?: string
  leftoverScore?: 1 | 2 | 3 | 4 | 5
  cleanupScore?: 1 | 2 | 3 | 4 | 5
  freezerFriendly?: boolean
  mealPrepFriendly?: boolean
  reheatsWell?: boolean
  costTier?: '$' | '$$' | '$$$'
}

const SEEDS: Seed[] = [
  {
    title: 'Slow Cooker Chicken Curry',
    description:
      'Everything goes in before you leave in the morning. It gets better the next day.',
    servings: 6,
    prep: 20,
    cook: 360,
    active: 20,
    methods: ['slow-cooker'],
    tags: ['easy', 'bulk', 'comfort-food'],
    equipment: ['Slow Cooker'],
    leftoverScore: 5,
    reheatsWell: true,
    freezerFriendly: true,
    costTier: '$$',
    ingredients: [
      '2 lbs boneless skinless chicken thighs',
      '2 large yellow onions, finely diced',
      '4 cloves garlic, minced',
      '1 tbsp fresh ginger, grated',
      '3 tbsp curry paste',
      '1 (14 oz) can coconut milk',
      '1 cup chicken broth',
      '2 tbsp tomato paste',
      '1 tsp salt',
      '3 cups spinach',
      'Fresh cilantro, for serving',
    ],
    steps: [
      'Put the chicken, onions, garlic and ginger into the slow cooker.',
      'Whisk the curry paste, coconut milk, broth, tomato paste and salt together, then pour it over the chicken.',
      'Cover and cook on low for 6 hours, or on high for 3 hours.',
      'Shred the chicken with two forks in the pot, then stir the spinach through and let it wilt for 5 minutes.',
      'Serve over rice with cilantro on top.',
    ],
    notes: 'Works better at 8 hours on low if you are out all day.',
  },
  {
    title: 'Instant Pot Beef Chili',
    description: 'A whole pot of chili in about forty minutes, most of it unattended.',
    servings: 6,
    prep: 15,
    cook: 35,
    active: 20,
    methods: ['instant-pot'],
    tags: ['bulk', 'cheap', 'comfort-food'],
    equipment: ['Instant Pot'],
    leftoverScore: 5,
    reheatsWell: true,
    freezerFriendly: true,
    costTier: '$',
    ingredients: [
      '2 lbs ground beef',
      '1 large yellow onion, diced',
      '1 red bell pepper, diced',
      '4 cloves garlic, minced',
      '3 tbsp chili powder',
      '1 tbsp cumin',
      '1 tsp smoked paprika',
      '2 (14 oz) cans diced tomatoes',
      '2 (14 oz) cans kidney beans, drained',
      '1 cup beef broth',
      '1 tsp salt',
    ],
    steps: [
      'Set the Instant Pot to sauté and brown the beef with the onion and pepper, about 8 minutes.',
      'Stir in the garlic, chili powder, cumin and paprika and cook for 1 minute.',
      'Add the tomatoes, beans, broth and salt. Scrape the bottom of the pot clean.',
      'Seal and cook on high pressure for 15 minutes, then let the pressure release naturally for 10 minutes.',
      'Taste for salt and serve.',
    ],
  },
  {
    title: 'Sheet Pan Chicken and Vegetables',
    description: 'One pan, one temperature, almost no cleanup.',
    servings: 6,
    prep: 15,
    cook: 40,
    active: 15,
    methods: ['sheet-pan', 'oven'],
    tags: ['easy', 'healthy', 'meal-prep'],
    equipment: ['Sheet Pan'],
    leftoverScore: 4,
    cleanupScore: 5,
    mealPrepFriendly: true,
    reheatsWell: true,
    costTier: '$$',
    ingredients: [
      '6 bone-in chicken thighs',
      '1.5 lbs baby potatoes, halved',
      '4 carrots, cut into chunks',
      '1 red onion, quartered',
      '3 tbsp olive oil',
      '1 tbsp italian seasoning',
      '1 tsp garlic powder',
      '1 tsp salt',
      '1/2 tsp black pepper',
      '1 lemon, cut into wedges',
    ],
    steps: [
      'Heat the oven to 425°F.',
      'Toss the potatoes, carrots and onion with 2 tbsp of the oil and half the seasoning, then spread them on a sheet pan.',
      'Rub the chicken with the remaining oil and seasoning and nestle it among the vegetables.',
      'Roast for 40 minutes, until the chicken reaches 175°F and the potatoes are browned.',
      'Squeeze the lemon over everything before serving.',
    ],
  },
  {
    title: 'Grilled Cheese and Tomato Soup',
    description: 'The twenty-minute answer to a Friday.',
    servings: 4,
    prep: 5,
    cook: 15,
    active: 20,
    methods: ['stovetop'],
    tags: ['easy', 'lazy-night', 'cheap', 'comfort-food'],
    equipment: ['Large Pot', 'Cast Iron Skillet'],
    leftoverScore: 2,
    cleanupScore: 4,
    costTier: '$',
    ingredients: [
      '8 slices sourdough bread',
      '8 oz cheddar cheese, grated',
      '4 tbsp butter, softened',
      '2 (14 oz) cans crushed tomatoes',
      '2 cups chicken broth',
      '1 yellow onion, diced',
      '2 tbsp olive oil',
      '1/2 cup heavy cream',
      '1 tsp sugar',
      '1 tsp salt',
    ],
    steps: [
      'Soften the onion in the olive oil in a large pot over medium heat, about 6 minutes.',
      'Add the tomatoes, broth, sugar and salt and simmer for 10 minutes.',
      'Blend the soup smooth, then stir in the cream and keep it warm.',
      'Butter the outsides of the bread, fill each sandwich with cheese, and cook in a skillet over medium heat until golden on both sides.',
      'Cut the sandwiches diagonally and serve with the soup.',
    ],
  },
  {
    title: 'One Pot Creamy Sausage Pasta',
    description: 'The pasta cooks in the sauce, so there is nothing to drain.',
    servings: 4,
    prep: 10,
    cook: 20,
    active: 25,
    methods: ['one-pot', 'stovetop'],
    tags: ['easy', 'comfort-food'],
    equipment: ['Large Pot'],
    leftoverScore: 3,
    cleanupScore: 5,
    costTier: '$',
    ingredients: [
      '1 lb italian sausage, casings removed',
      '1 yellow onion, diced',
      '3 cloves garlic, minced',
      '12 oz penne',
      '3 cups chicken broth',
      '1 (14 oz) can diced tomatoes',
      '3/4 cup heavy cream',
      '3 cups spinach',
      '1/2 cup parmesan, grated',
      '1/2 tsp red pepper flakes',
    ],
    steps: [
      'Brown the sausage in a large pot over medium-high heat, breaking it up as it cooks.',
      'Add the onion and cook for 4 minutes, then the garlic and pepper flakes for 1 minute more.',
      'Stir in the pasta, broth and tomatoes. Bring to a boil, then simmer for 12 minutes, stirring now and then.',
      'Stir in the cream, spinach and parmesan and cook for 2 minutes until the spinach wilts and the sauce thickens.',
    ],
  },
  {
    title: 'Slow Cooker Pulled Pork',
    description: 'One shoulder, one night, and lunches for the rest of the week.',
    servings: 10,
    prep: 15,
    cook: 480,
    active: 15,
    methods: ['slow-cooker'],
    tags: ['bulk', 'cheap', 'freezer', 'meal-prep'],
    equipment: ['Slow Cooker'],
    leftoverScore: 5,
    freezerFriendly: true,
    mealPrepFriendly: true,
    reheatsWell: true,
    costTier: '$',
    ingredients: [
      '4 lbs pork shoulder',
      '2 tbsp brown sugar',
      '1 tbsp smoked paprika',
      '1 tbsp salt',
      '2 tsp garlic powder',
      '1 tsp black pepper',
      '1 yellow onion, sliced',
      '1 cup BBQ sauce',
      '1/2 cup apple juice',
    ],
    steps: [
      'Mix the sugar, paprika, salt, garlic powder and pepper and rub it all over the pork.',
      'Lay the onion in the slow cooker, set the pork on top and pour the apple juice around it.',
      'Cover and cook on low for 8 hours, until the meat pulls apart with a fork.',
      'Shred the pork, discard the excess fat, and stir the bbq sauce through it.',
    ],
    notes: 'Freezes well in 2-cup portions with a little of the cooking liquid.',
  },
  {
    title: 'Weeknight Fried Rice',
    description: 'Built for leftover rice and whatever vegetables are going soft.',
    servings: 4,
    prep: 10,
    cook: 12,
    active: 20,
    methods: ['stovetop', 'one-pot'],
    tags: ['easy', 'cheap', 'lazy-night'],
    equipment: ['Cast Iron Skillet'],
    leftoverScore: 3,
    cleanupScore: 4,
    costTier: '$',
    ingredients: [
      '4 cups cooked rice, cold',
      '3 eggs, beaten',
      '2 cups frozen peas and carrots',
      '4 green onions, sliced',
      '3 cloves garlic, minced',
      '3 tbsp soy sauce',
      '1 tbsp sesame oil',
      '2 tbsp vegetable oil',
    ],
    steps: [
      'Heat the vegetable oil in a large skillet over high heat.',
      'Scramble the eggs quickly and set them aside.',
      'Add the peas and carrots and the garlic and cook for 2 minutes.',
      'Add the rice and press it flat against the pan for 2 minutes at a time so it crisps.',
      'Return the eggs, add the soy sauce, sesame oil and green onions, and toss for 1 minute.',
    ],
    notes: 'Cold rice from the fridge fries far better than fresh.',
  },
  {
    title: 'Instant Pot Lentil Soup',
    description: 'Cheap, filling, and it freezes flat.',
    servings: 8,
    prep: 10,
    cook: 25,
    active: 15,
    methods: ['instant-pot'],
    tags: ['cheap', 'healthy', 'bulk', 'freezer'],
    equipment: ['Instant Pot'],
    leftoverScore: 5,
    freezerFriendly: true,
    mealPrepFriendly: true,
    reheatsWell: true,
    costTier: '$',
    ingredients: [
      '2 cups brown lentils, rinsed',
      '1 yellow onion, diced',
      '3 carrots, diced',
      '3 stalks celery, diced',
      '4 cloves garlic, minced',
      '1 (14 oz) can diced tomatoes',
      '8 cups vegetable broth',
      '2 tsp cumin',
      '1 tsp smoked paprika',
      '2 bay leaves',
      '2 tbsp olive oil',
      '1 tsp salt',
    ],
    steps: [
      'Sauté the onion, carrot and celery in the olive oil for 5 minutes.',
      'Add the garlic, cumin and paprika and cook for 1 minute.',
      'Add the lentils, tomatoes, broth, bay leaves and salt.',
      'Seal and cook on high pressure for 15 minutes, then release the pressure naturally for 10 minutes.',
      'Fish out the bay leaves and season to taste.',
    ],
  },
  {
    title: 'Black Bean Quesadillas',
    description: 'Fifteen minutes, mostly pantry.',
    servings: 4,
    prep: 10,
    cook: 10,
    active: 15,
    methods: ['stovetop'],
    tags: ['cheap', 'easy', 'lazy-night', 'work-lunch'],
    equipment: ['Cast Iron Skillet'],
    leftoverScore: 2,
    cleanupScore: 5,
    costTier: '$',
    ingredients: [
      '8 flour tortillas',
      '2 (14 oz) cans black beans, drained',
      '2 cups cheddar cheese, grated',
      '1 tsp cumin',
      '1 tsp chili powder',
      '1/2 cup salsa',
      '2 tbsp vegetable oil',
      '1 avocado, sliced',
    ],
    steps: [
      'Mash the beans roughly with the cumin, chili powder and salsa.',
      'Spread the mixture over half of each tortilla, top with cheese and fold.',
      'Cook in a lightly oiled skillet over medium heat for 3 minutes a side, until crisp.',
      'Cut into wedges and serve with avocado.',
    ],
  },
  {
    title: 'Roast Chicken with Potatoes',
    description: 'Sunday dinner that turns into Monday lunch.',
    servings: 6,
    prep: 20,
    cook: 75,
    active: 20,
    methods: ['oven'],
    tags: ['bulk', 'comfort-food'],
    equipment: ['Dutch Oven'],
    leftoverScore: 5,
    reheatsWell: true,
    costTier: '$$',
    ingredients: [
      '1 whole chicken, about 4 lbs',
      '2 lbs baby potatoes',
      '1 head garlic, halved',
      '1 lemon, halved',
      '3 tbsp butter, softened',
      '2 tbsp olive oil',
      '2 tsp salt',
      '1 tsp black pepper',
      '4 sprigs rosemary',
    ],
    steps: [
      'Heat the oven to 400°F and pat the chicken dry.',
      'Rub the butter under and over the skin, then season the bird inside and out.',
      'Put the lemon and two rosemary sprigs in the cavity.',
      'Toss the potatoes and garlic with the olive oil and the rest of the rosemary and scatter them around the chicken.',
      'Roast for 75 minutes, until the thigh reaches 175°F.',
      'Rest the chicken for 15 minutes before carving.',
    ],
    notes: 'Simmer the carcass with the leftover garlic for stock.',
  },
  {
    title: 'Big Batch Turkey Meatballs',
    description: 'Make a tray on Sunday, eat them four different ways.',
    servings: 8,
    prep: 20,
    cook: 25,
    active: 25,
    methods: ['oven', 'sheet-pan'],
    tags: ['meal-prep', 'freezer', 'bulk'],
    equipment: ['Sheet Pan'],
    leftoverScore: 5,
    freezerFriendly: true,
    mealPrepFriendly: true,
    reheatsWell: true,
    costTier: '$$',
    ingredients: [
      '2 lbs ground turkey',
      '1 cup breadcrumbs',
      '2 eggs',
      '1/2 cup parmesan, grated',
      '4 cloves garlic, minced',
      '1/4 cup parsley, finely chopped',
      '1 tsp salt',
      '1 tsp italian seasoning',
      '1/2 tsp black pepper',
    ],
    steps: [
      'Heat the oven to 400°F and line a sheet pan with parchment.',
      'Mix everything together with your hands until just combined — overworking makes them tough.',
      'Roll into 32 meatballs and space them out on the pan.',
      'Bake for 25 minutes, until cooked through and browned.',
    ],
    notes: 'Freeze half on the tray, then bag them once solid.',
  },
  {
    title: 'Overnight Oats',
    description: 'Five minutes tonight, breakfast for four mornings.',
    servings: 4,
    prep: 5,
    cook: 0,
    active: 5,
    methods: ['no-cook'],
    mealTypes: ['breakfast'],
    tags: ['meal-prep', 'healthy', 'cheap'],
    equipment: [],
    leftoverScore: 5,
    cleanupScore: 5,
    mealPrepFriendly: true,
    costTier: '$',
    ingredients: [
      '2 cups rolled oats',
      '2 cups milk',
      '1 cup yogurt',
      '2 tbsp maple syrup',
      '2 tbsp chia seeds',
      '1 tsp vanilla extract',
      '1 cup blueberries',
    ],
    steps: [
      'Stir everything except the blueberries together in a large container.',
      'Divide between four jars and refrigerate overnight.',
      'Top with blueberries in the morning.',
    ],
  },
]

export function starterRecipeDrafts(): RecipeDraft[] {
  return SEEDS.map((seed) => {
    const draft = toRecipeDraft({
      title: seed.title,
      description: seed.description,
      servings: seed.servings,
      prepTimeMinutes: seed.prep,
      cookTimeMinutes: seed.cook,
      ingredientLines: seed.ingredients,
      instructionTexts: seed.steps,
      tags: seed.tags,
      notes: seed.notes,
      sourceName: 'MealHelp starter recipes',
    })

    return {
      ...draft,
      cookingMethods: seed.methods,
      mealTypes: seed.mealTypes ?? ['dinner'],
      equipment: seed.equipment,
      activeTimeMinutes: seed.active,
      leftoverScore: seed.leftoverScore,
      cleanupScore: seed.cleanupScore,
      freezerFriendly: seed.freezerFriendly,
      mealPrepFriendly: seed.mealPrepFriendly,
      reheatsWell: seed.reheatsWell,
      costTier: seed.costTier,
    }
  })
}

export const STARTER_RECIPE_COUNT = SEEDS.length
