import type { PlannedMeal } from '@/models'

/**
 * Which cooking session a leftover night eats from.
 *
 * Leftovers are the point of planning a week this way, so the week has to
 * *show* them: Tuesday is not "Chili again", it is Monday's chili, and the
 * two cards belong to each other. The planner does not always write the link
 * down — a week generated by the wizard stores a leftover night as a meal of
 * the same recipe — so it is derived here instead: the nearest earlier night
 * in the same week that actually cooked that recipe.
 *
 * Deriving rather than requiring a stored id also means a leftover night
 * dragged to another day re-links itself, and a leftover night whose source
 * was deleted simply stops claiming a source rather than pointing at nothing.
 */

export interface LeftoverLink {
  /** The meal this leftover night eats from. */
  sourceId: string
  sourceDate: string
}

export interface LeftoverGraph {
  /** Leftover meal id → where it came from. */
  sourceOf: Map<string, LeftoverLink>
  /** Cooking meal id → the dates it feeds, earliest first. */
  feeds: Map<string, string[]>
}

function chronological(meals: PlannedMeal[]): PlannedMeal[] {
  return [...meals].sort(
    (a, b) => a.date.localeCompare(b.date) || (a.order ?? 0) - (b.order ?? 0),
  )
}

export function leftoverGraph(meals: PlannedMeal[]): LeftoverGraph {
  const ordered = chronological(meals)
  const sourceOf = new Map<string, LeftoverLink>()
  const feeds = new Map<string, string[]>()

  for (const meal of ordered) {
    if (meal.kind !== 'leftover') continue

    // An explicit link wins when the planner wrote one down.
    const explicit = meal.sourcePlannedMealId
      ? ordered.find((candidate) => candidate.id === meal.sourcePlannedMealId)
      : undefined

    const source =
      explicit ??
      [...ordered]
        .reverse()
        .find(
          (candidate) =>
            candidate.kind === 'recipe' &&
            candidate.recipeId === meal.recipeId &&
            candidate.date < meal.date,
        )

    if (!source) continue

    sourceOf.set(meal.id, { sourceId: source.id, sourceDate: source.date })
    feeds.set(source.id, [...(feeds.get(source.id) ?? []), meal.date])
  }

  return { sourceOf, feeds }
}
